In [1]:
import numpy as np
import pandas as pd

In [2]:
concrete_data = pd.read_csv('https://ibm.box.com/shared/static/svl8tu7cmod6tizo6rk0ke4sbuhtpdfx.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
# split data into predictors and target

concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']]
target = concrete_data['Strength']

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [10]:
# Normalizing

predictors_norm = (predictors - predictors.mean()) / (predictors.std())
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [11]:
n_cols = predictors_norm.shape[1]
n_cols

8

In [12]:
import keras

In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
# Build a Neural network

def regression_model():
    #create model
    model = Sequential()
    model.add(Dense(50, activation = 'relu', input_shape=(n_cols,)))
    model.add(Dense(50, activation = 'relu'))
    model.add(Dense(1))
    
    #compile model
    model.compile(optimizer = 'adam', loss = 'mean_squared_error')
    return model

In [18]:
# Train and test the Network

model = regression_model()

model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 0s - loss: 1654.9760 - val_loss: 1160.8673
Epoch 2/100
23/23 - 0s - loss: 1548.2771 - val_loss: 1048.4794
Epoch 3/100
23/23 - 0s - loss: 1359.6334 - val_loss: 856.8556
Epoch 4/100
23/23 - 0s - loss: 1039.9738 - val_loss: 598.2336
Epoch 5/100
23/23 - 0s - loss: 651.4476 - val_loss: 341.4850
Epoch 6/100
23/23 - 0s - loss: 345.7315 - val_loss: 197.8328
Epoch 7/100
23/23 - 0s - loss: 239.5133 - val_loss: 160.9366
Epoch 8/100
23/23 - 0s - loss: 216.8539 - val_loss: 159.4585
Epoch 9/100
23/23 - 0s - loss: 203.5818 - val_loss: 160.5443
Epoch 10/100
23/23 - 0s - loss: 195.8522 - val_loss: 159.4224
Epoch 11/100
23/23 - 0s - loss: 188.4904 - val_loss: 155.0716
Epoch 12/100
23/23 - 0s - loss: 182.7853 - val_loss: 151.7230
Epoch 13/100
23/23 - 0s - loss: 178.6312 - val_loss: 152.1730
Epoch 14/100
23/23 - 0s - loss: 173.9492 - val_loss: 149.3097
Epoch 15/100
23/23 - 0s - loss: 170.2577 - val_loss: 150.8259
Epoch 16/100
23/23 - 0s - loss: 166.9190 - val_loss: 147.5034
Epoch 17/100
23/23 - 0s - loss: 164.0504 - val_loss: 146.0278
Epoch 18/100
23/23 - 0s - loss: 161.1964 - val_loss: 146.0747
Epoch 19/100
23/23 - 0s - loss: 158.2491 - val_loss: 147.8295
Epoch 20/100
23/23 - 0s - loss: 156.3803 - val_loss: 144.8612
Epoch 21/100
23/23 - 0s - loss: 154.1340 - val_loss: 147.9986
Epoch 22/100
23/23 - 0s - loss: 151.7818 - val_loss: 145.1564
Epoch 23/100
23/23 - 0s - loss: 150.0682 - val_loss: 147.1665
Epoch 24/100
23/23 - 0s - loss: 147.7424 - val_loss: 145.8220
Epoch 25/100
23/23 - 0s - loss: 146.3698 - val_loss: 143.2749
Epoch 26/100
23/23 - 0s - loss: 144.5408 - val_loss: 145.4924
Epoch 27/100
23/23 - 0s - loss: 143.2475 - val_loss: 147.9394
Epoch 28/100
23/23 - 0s - loss: 141.3785 - val_loss: 145.0185
Epoch 29/100
23/23 - 0s - loss: 139.6609 - val_loss: 147.5866
Epoch 30/100
23/23 - 0s - loss: 138.8055 - val_loss: 148.6105
Epoch 31/100
23/23 - 0s - loss: 136.7365 - val_loss: 146.0361
Epoch 32/100
23/23 - 0s - loss: 135.6214 - val_loss: 147.8520
Epoch 33/100
23/23 - 0s - loss: 134.6890 - val_loss: 149.0376
Epoch 34/100
23/23 - 0s - loss: 133.2700 - val_loss: 149.4632
Epoch 35/100
23/23 - 0s - loss: 131.6062 - val_loss: 150.7331
Epoch 36/100
23/23 - 0s - loss: 130.5713 - val_loss: 149.7176
Epoch 37/100
23/23 - 0s - loss: 128.5439 - val_loss: 150.7600
Epoch 38/100
23/23 - 0s - loss: 127.4818 - val_loss: 148.8493
Epoch 39/100
23/23 - 0s - loss: 126.2563 - val_loss: 151.1602
Epoch 40/100
23/23 - 0s - loss: 124.9854 - val_loss: 150.5686
Epoch 41/100
23/23 - 0s - loss: 124.7976 - val_loss: 150.1633
Epoch 42/100
23/23 - 0s - loss: 122.0125 - val_loss: 149.7484
Epoch 43/100
23/23 - 0s - loss: 120.4725 - val_loss: 149.6220
Epoch 44/100
23/23 - 0s - loss: 119.2056 - val_loss: 149.9688
Epoch 45/100
23/23 - 0s - loss: 118.1196 - val_loss: 151.5328
Epoch 46/100
23/23 - 0s - loss: 116.1136 - val_loss: 149.0910
Epoch 47/100
23/23 - 0s - loss: 114.7603 - val_loss: 149.9468
Epoch 48/100
23/23 - 0s - loss: 113.1290 - val_loss: 152.3329
Epoch 49/100
23/23 - 0s - loss: 111.3230 - val_loss: 149.0437
Epoch 50/100
23/23 - 0s - loss: 109.7811 - val_loss: 150.8302
Epoch 51/100
23/23 - 0s - loss: 108.2048 - val_loss: 147.4795
Epoch 52/100
23/23 - 0s - loss: 106.7483 - val_loss: 147.7005
Epoch 53/100
23/23 - 0s - loss: 104.6173 - val_loss: 146.2061
Epoch 54/100
23/23 - 0s - loss: 102.8603 - val_loss: 145.0658
Epoch 55/100
23/23 - 0s - loss: 100.6557 - val_loss: 143.1973
Epoch 56/100
23/23 - 0s - loss: 98.5405 - val_loss: 141.5132
Epoch 57/100
23/23 - 0s - loss: 96.8269 - val_loss: 140.8849
Epoch 58/100
23/23 - 0s - loss: 94.4006 - val_loss: 138.7785
Epoch 59/100
23/23 - 0s - loss: 91.9752 - val_loss: 137.9840
Epoch 60/100
23/23 - 0s - loss: 90.5534 - val_loss: 137.7594
Epoch 61/100
23/23 - 0s - loss: 88.4612 - val_loss: 134.9012
Epoch 62/100
23/23 - 0s - loss: 85.8939 - val_loss: 132.5184
Epoch 63/100
23/23 - 0s - loss: 83.8952 - val_loss: 131.9297
Epoch 64/100
23/23 - 0s - loss: 81.6016 - val_loss: 134.0758
Epoch 65/100
23/23 - 0s - loss: 79.0667 - val_loss: 129.1940
Epoch 66/100
23/23 - 0s - loss: 76.8805 - val_loss: 127.0811
Epoch 67/100
23/23 - 0s - loss: 74.6529 - val_loss: 121.7118
Epoch 68/100
23/23 - 0s - loss: 72.1446 - val_loss: 121.5379
Epoch 69/100
23/23 - 0s - loss: 69.9619 - val_loss: 116.1258
Epoch 70/100
23/23 - 0s - loss: 67.9005 - val_loss: 119.0405
Epoch 71/100
23/23 - 0s - loss: 66.1796 - val_loss: 118.3327
Epoch 72/100
23/23 - 0s - loss: 64.6154 - val_loss: 107.8360
Epoch 73/100
23/23 - 0s - loss: 62.8981 - val_loss: 111.1998
Epoch 74/100
23/23 - 0s - loss: 61.4666 - val_loss: 109.9939
Epoch 75/100
23/23 - 0s - loss: 58.5811 - val_loss: 115.7317
Epoch 76/100
23/23 - 0s - loss: 56.7334 - val_loss: 110.2789
Epoch 77/100
23/23 - 0s - loss: 55.3349 - val_loss: 115.9408
Epoch 78/100
23/23 - 0s - loss: 54.2735 - val_loss: 113.7179
Epoch 79/100
23/23 - 0s - loss: 53.2984 - val_loss: 109.5315
Epoch 80/100
23/23 - 0s - loss: 50.9564 - val_loss: 109.0198
Epoch 81/100
23/23 - 0s - loss: 50.4802 - val_loss: 104.9448
Epoch 82/100
23/23 - 0s - loss: 48.9713 - val_loss: 105.2955
Epoch 83/100
23/23 - 0s - loss: 47.9828 - val_loss: 104.1882
Epoch 84/100
23/23 - 0s - loss: 46.8493 - val_loss: 109.6196
Epoch 85/100
23/23 - 0s - loss: 46.1089 - val_loss: 105.6275
Epoch 86/100
23/23 - 0s - loss: 45.0046 - val_loss: 108.8655
Epoch 87/100
23/23 - 0s - loss: 43.5860 - val_loss: 107.6247
Epoch 88/100
23/23 - 0s - loss: 42.6048 - val_loss: 108.3091
Epoch 89/100
23/23 - 0s - loss: 42.8159 - val_loss: 105.5838
Epoch 90/100
23/23 - 0s - loss: 41.4047 - val_loss: 106.9830
Epoch 91/100
23/23 - 0s - loss: 40.6215 - val_loss: 112.9084
Epoch 92/100
23/23 - 0s - loss: 40.1985 - val_loss: 100.2048
Epoch 93/100
23/23 - 0s - loss: 39.6312 - val_loss: 114.5699
Epoch 94/100
23/23 - 0s - loss: 38.8829 - val_loss: 102.9968
Epoch 95/100
23/23 - 0s - loss: 38.2978 - val_loss: 104.4311
Epoch 96/100
23/23 - 0s - loss: 38.1070 - val_loss: 108.7137
Epoch 97/100
23/23 - 0s - loss: 37.2936 - val_loss: 112.8007
Epoch 98/100
23/23 - 0s - loss: 37.0955 - val_loss: 106.4982
Epoch 99/100
23/23 - 0s - loss: 36.3064 - val_loss: 114.0163
Epoch 100/100
23/23 - 0s - loss: 35.9826 - val_loss: 107.3530

In [19]:
# Train and test the Network

model = regression_model()

model.fit(predictors_norm, target, validation_split=0.4, epochs=30, verbose=2)

Epoch 1/30
20/20 - 0s - loss: 1801.3127 - val_loss: 1007.1235
Epoch 2/30
20/20 - 0s - loss: 1661.0883 - val_loss: 902.0663
Epoch 3/30
20/20 - 0s - loss: 1456.0615 - val_loss: 759.8129
Epoch 4/30
20/20 - 0s - loss: 1166.9426 - val_loss: 584.8877
Epoch 5/30
20/20 - 0s - loss: 821.7437 - val_loss: 410.6567
Epoch 6/30
20/20 - 0s - loss: 506.2560 - val_loss: 277.3275
Epoch 7/30
20/20 - 0s - loss: 325.8887 - val_loss: 204.2382
Epoch 8/30
20/20 - 0s - loss: 266.5238 - val_loss: 178.2965
Epoch 9/30
20/20 - 0s - loss: 245.0518 - val_loss: 169.1130
Epoch 10/30
20/20 - 0s - loss: 230.0971 - val_loss: 162.2428
Epoch 11/30
20/20 - 0s - loss: 220.7407 - val_loss: 156.5800
Epoch 12/30
20/20 - 0s - loss: 212.3041 - val_loss: 154.4086
Epoch 13/30
20/20 - 0s - loss: 205.4904 - val_loss: 150.0864
Epoch 14/30
20/20 - 0s - loss: 199.7858 - val_loss: 149.2175
Epoch 15/30
20/20 - 0s - loss: 194.1026 - val_loss: 148.4710
Epoch 16/30
20/20 - 0s - loss: 189.4340 - val_loss: 145.2088
Epoch 17/30
20/20 - 0s - loss: 184.9865 - val_loss: 143.3299
Epoch 18/30
20/20 - 0s - loss: 182.4929 - val_loss: 141.6739
Epoch 19/30
20/20 - 0s - loss: 177.9967 - val_loss: 140.3596
Epoch 20/30
20/20 - 0s - loss: 174.0087 - val_loss: 140.6354
Epoch 21/30
20/20 - 0s - loss: 171.1413 - val_loss: 138.1717
Epoch 22/30
20/20 - 0s - loss: 168.0810 - val_loss: 139.0015
Epoch 23/30
20/20 - 0s - loss: 165.3615 - val_loss: 138.1490
Epoch 24/30
20/20 - 0s - loss: 162.4543 - val_loss: 138.5823
Epoch 25/30
20/20 - 0s - loss: 160.4666 - val_loss: 137.8104
Epoch 26/30
20/20 - 0s - loss: 158.3520 - val_loss: 138.5578
Epoch 27/30
20/20 - 0s - loss: 155.7038 - val_loss: 137.6386
Epoch 28/30
20/20 - 0s - loss: 154.0379 - val_loss: 137.8851
Epoch 29/30
20/20 - 0s - loss: 152.0170 - val_loss: 137.9377
Epoch 30/30
20/20 - 0s - loss: 149.9984 - val_loss: 137.9287